version: "2"

networks:
  db:
    driver: bridge
  redis:
    driver: bridge
  sharetribe:
    driver: bridge
    
services:
  db:
    image: mysql:5.7
    networks:
      - db
    volumes:
      - "./data/mysql:/var/lib/mysql"
    environment:
      MYSQL_USER: sharetribe
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: sharetribe_production
      MYSQL_ROOT_PASSWORD: secret

  redis:
    image: redis:latest
    networks:
      - redis
    volumes:
      - "./data/redis:/data"
      
  sharetribe:
    image: sharetribe:0.1
    networks:
      - db
      - redis
      - sharetribe   
    #CURRENT_UID=$(id -u):$(id -g) docker-compose up    
    #user: ${CURRENT_UID}
    build:
      context: .
      dockerfile: Dockerfile.sharetribe
    links:
      - db:mysql
      - redis:redis
    volumes:
      - "./data:/extvol"
    depends_on:
      - db
      - redis
    ports:
      - "80:80"
      - "443:443"
    environment:
      QUEUES: default,paperclip,mailers
      MAGICK_MAP_LIMIT: 64MiB
      MAGICK_MEMORY_LIMIT: 256MiB
      MAGICK_TIME_LIMIT: 30
      redis_host: redis
      SPHINX_HOST: localhost
