version: "2"
services:
  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    volumes:
    - "./data/mysql:/var/lib/mysql"
    environment:
      MYSQL_USER: sharetribe
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: sharetribe_production
      MYSQL_ROOT_PASSWORD: secret

  dbinit:
    build:
      context: .
      dockerfile: Dockerfile.sharetribe
    command: '/bin/bash -l -c "bundle exec rake db:create db:structure:load"'
    links:
      - db:mysql
    depends_on:
      - db
    environment:
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1

  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    volumes:
    - "./data/redis:/data"
      
  gensphinxcfg:
    build:
      context: .
      dockerfile: Dockerfile.sharetribe
    command: 'bundle exec rake ts:configure'
    links:
      - db:mysql
    depends_on:
      - db
    volumes:
      - ./data:/sharetribe/data
      
  sharetribe:
    image: sharetribe:0.1
    build:
      context: .
      dockerfile: Dockerfile.sharetribe
    links:
      - db:mysql
      - redis:redis
    volumes:
      - ./data:/sharetribe/data
      - ./data/sharetribe/public/system/images:/opt/app/public/system/images
      - ./data/sharetribe/public/system/paypal:/opt/app/public/system/paypal
    depends_on:
      - db
      - redis
    ports:
      - "9001:9001"
      - "80:3000"
    environment:
      QUEUES: default,paperclip,mailers
      MAGICK_MAP_LIMIT: 64MiB
      MAGICK_MEMORY_LIMIT: 256MiB
      MAGICK_TIME_LIMIT: 30
      redis_host: redis
      SPHINX_HOST: localhost
