version: "2"
services:
  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    volumes:
    - "./data/mysql:/var/lib/mysql"
    environment:
      MYSQL_USER: sharetribe
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: sharetribe_production
      MYSQL_ROOT_PASSWORD: secret

  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    volumes:
    - "./data/redis:/data"
      
  sharetribe:
    image: sharetribe:0.1
    build:
      context: .
      dockerfile: Dockerfile.sharetribe
    links:
      - db:mysql
      - redis:redis
    volumes:
      - "./data:/extvol"
    depends_on:
      - db
      - redis
    ports:
      - "9001:9001"
      - "80:3000"
      - "8080:8080"
      - "8443:8443"
    environment:
      QUEUES: default,paperclip,mailers
      MAGICK_MAP_LIMIT: 64MiB
      MAGICK_MEMORY_LIMIT: 256MiB
      MAGICK_TIME_LIMIT: 30
      redis_host: redis
      SPHINX_HOST: localhost
